
'''
URL arguments that you add to a query string are the simpliest way to pass data to a web app, so let's start with them.

A query string looks like the following:

example.com?arg1=value1&arg2=value2


Query strings are useful for passing data that doesn't require the user to take action. You could generate a query string somewhere in your app and append it a URL so when a user makes a request, the data is automatically passed for them. A query string can also be generated by forms that have GET as the method.



'''



from flask import Flask, request

app = Flask(__name__)

@app.route('/post', methods=['POST'])
def post_route():
    if request.method == 'POST':

        data = request.get_json()

        print('Data Received: "{data}"'.format(data=data))
        return "Request Processed."+'Data Received: "{data}"'.format(data=data)

app.run(host = '0.0.0.0',port= 8000)



#curl localhost:5000/post -d '{"foo": "bar"}' -H 'Content-Type: application/json'