(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.App_InfraBG = function() {
	this.initialize(img.App_InfraBG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.mc_text3a = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1_copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3C3C41").s().p("AgTA5QAHAAADgEQADgEAAgIIAAgWQAAgQAOgDQgOgDAAgQIAAgWQAAgOgNgBIAAgMQAbABAAAXIAAAXQAAAPAMABIAAALQgMAAAAAQIAAAXQAAAXgbABg");
	this.shape.setTransform(4.575,14.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_text3a, new cjs.Rectangle(0,0,87.6,25.3), null);


(lib.mc_text2c = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1_copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag0CsQgJgOgBgbQAAgeALgPQAKgPAUAAQAjgBABA6QAAAdgLAPQgJAPgUAAQgRAAgKgPgAgrCCQAAAqAUAAQAUAAAAgrQAAgsgTAAQgVAAAAAtgAjkCsQgKgOAAgbQgBgeALgPQAKgPATAAQAmgBgBA6QAAAdgKAPQgKAPgTAAQgSAAgJgPgAjcCCQAAAqAUAAQAUAAAAgrQAAgsgTAAQgVAAAAAtgAoPCvQgLgLAAgSQAAgTAMgMQAMgNATAAQAMAAAHAFIAAARQgIgHgJAAQgMAAgHAIQgIAIAAAMQABAMAGAIQAIAHALAAQAKAAAIgHIAAAQQgJAGgNAAQgSAAgLgMgAqjC0QgGgHAAgKQAAgXAagEIAYgCQgBgSgQAAQgOAAgMAKIAAgQQAOgIAQAAQAeAAAAAfIAAAzIgRAAIAAgMQgJAPgQAAQgMAAgHgHgAqICTQgIACgEADQgEACAAAHQAAAFAEAEQADACAHAAQAIAAAFgFQAGgGAAgJIAAgHgAupC4QgHgDgFgEQgFgEgCgHQgDgFgBgIQAAgEACgFQABgFADgEIAGgHQADgCAFgCQgHgFgFgFQgDgHAAgIQgBgGADgFQADgFAEgEQAFgEAFgCQAHgDAHABQAHgBAGADQAGACAFAEQAEADACAGQADAFAAAGQAAAIgEAHQgFAFgGAFQAFACADACQAEADACAEQADAEABAFQABAFABAEQAAAIgEAFQgCAHgFAEQgFAEgHADQgHADgIAAQgIAAgHgDgAuiCFQgDABgDADQgDADgBAEQgCADAAAFIACAJIADAGQADACAEACIAIABIAIgBQADgBADgEQADgCABgEQABgEABgEIgCgIQgBgEgDgDQgDgDgDgBQgEgCgEAAQgFAAgDACgAugBWQgEABgCADIgDAEQgBADAAAEQAAAEABADIADAFIAGAEIAGAAIAGAAIAFgEIADgFIABgHIgBgHIgDgEQgCgDgDgBIgGgCQgDAAgDACgAiUC4IAAgIQAAgFABgFIAEgJIAGgHIAHgHIAWgTIAGgHIACgGQACgDAAgFQAAgEgCgDQgBgEgCgCQgDgCgDgBIgIgCQgGABgHADQgIADgGAHIAAgSIAOgIIAIgCIAJAAQAIAAAFABQAGACAFAFQAEAEADAFQADAGgBAHQAAAHgBAGQgCAFgDAFIgHAJIgbAWIgGAHQgCADAAAEIAAAAIAyAAIAAAPgAlFC4IAAgIQgBgFACgFIAEgJIAGgHIAHgHIAWgTIAFgHIADgGQACgDAAgFQAAgEgCgDQgBgEgCgCQgDgCgDgBIgIgCQgHABgGADQgIADgGAHIAAgSIAOgIIAIgCIAJAAQAIAAAFABQAHACAEAFQAEAEADAFQADAGAAAHQgBAHgCAGQgBAFgDAFIgIAJIgbAWIgGAHQgCADAAAEIAAAAIAzAAIAAAPgAmVC4IAAgrQABgYgRAAQgHAAgGAHQgFAHgBALIAAAqIgSAAIAAh2IASAAIAAA0IABAAQAJgQARAAQAbAAgBAhIAAAxgApQC4IAAhPIASAAIAAAQQAEgIAFgFQAGgFAGAAQAFAAACACIAAARQgCgDgHAAQgIAAgFAIQgGAHAAAMIAAAmgArPC4IABheIAAAAIgDALIgiBTIgMAAIgihTIgDgLIABBeIgRAAIAAhwIAaAAIAiBYIAihYIAZAAIAABwgAvoC4IAAhcIgLAGIgNAEIAAgPIAIgDIAagOIAIAAIAABygAuCgeIAAh1IASAAIAAAOQAJgQASAAQAQAAAIALQAJAKAAATQAAATgKAMQgJANgRAAQgQAAgIgOIAAAxgAtqh/QgGAGAAALIAAAKQAAAIAGAGQAFAHAIgBQALABAFgJQAGgHAAgOQAAgMgFgGQgGgIgIABQgLgBgFAIgAPchYIAAgtIgOAAIAAgOIAOAAIAAgTIASgEIAAAXIATAAIAAAOIgTAAIAAAoQAAAHACAEQADACAGAAQAEAAAEgCIAAAOQgFADgJAAQgYAAABgXgAI0hjIAAgwIASAAIAAAuQAAAWARgBQAHABAGgHQAFgFAAgKIAAguIASAAIAABQIgSAAIAAgNIAAAAQgIAPgRAAQgdAAABgigAHyhBIgQgEIgHgCIAAgTIAHADIAHAEIAIACIAHABQAMAAAFgFQAHgDAAgIQAAgDgCgEIgGgFIgcgQQgFgCgEgFQgEgDgCgFQgCgEAAgHQAAgIADgGQAEgFAGgEQAGgEAIgCQAGgCAJAAQARAAAIAEIAAASQgKgGgOgBIgIACQgFAAgDACQgEABgCADQgCAEAAADQABAEABADIAFAFIAHAFIAVAKQAGAEAEAEQAEAEACAFQACAFAAAGQAAAIgDAHQgEAFgGAEQgFAEgIABQgIACgIAAgAE3hHQgHgHAAgKQAAgXAagEIAXgDQAAgRgPAAQgPgBgLALIAAgRQAMgHARAAQAeAAAAAeIAAA0IgSAAIAAgNQgIAPgQAAQgMAAgGgGgAFRhoQgIABgEADQgEACAAAIQAAAEAEAEQAEADAFAAQAJAAAGgGQAEgGAAgIIAAgHgADXhjIAAgwIASAAIAAAuQAAAWARgBQAIABAFgHQAGgFgBgKIAAguIATAAIAABQIgTAAIAAgNIAAAAQgIAPgRAAQgcAAAAgigACkhYIAAgtIgNAAIAAgOIANAAIAAgTIASgEIAAAXIAUAAIAAAOIgUAAIAAAoQAAAHADAEQACACAHAAQAEAAAEgCIAAAOQgGADgJAAQgXAAAAgXgAimhMQgLgLAAgTQAAgTAMgMQALgMAQAAQAQAAAKAKQAIALABATIAAAHIg3AAQAAALAHAGQAGAGAMAAQANAAALgIIAAAPQgMAHgRAAQgTAAgJgLgAh5hzQAAgKgFgFQgEgGgIABQgIgBgGAGQgEAGgCAJIAlAAIAAAAgAjxhMQgKgMgBgRQABgUALgMQAMgMAUAAQALAAAIAEIAAARQgIgGgKAAQgLgBgIAJQgHAHAAANQAAAMAHAHQAHAIALgBQALABAIgIIAAAQQgJAGgNAAQgTAAgLgLgAmQhjIAAgwIATAAIAAAuQAAAWAQgBQAIABAGgHQAEgFABgKIAAguIASAAIAABQIgSAAIAAgNIgBAAQgIAPgQAAQgdAAAAgigAnohNQgLgKAAgTQAAgUAMgLQALgMATAAQAUAAAKALQALALAAAUQAAATgMALQgLAMgTAAQgTAAgLgMgAnah/QgHAIABANQgBAMAHAHQAGAIAKgBQALABAGgIQAGgGAAgOQAAgNgGgHQgGgHgLAAQgKAAgGAHgAoxhBIgQgEIgHgCIAAgTIAHADIAHAEIAIACIAHABQAMAAAFgFQAHgDAAgIQgBgDgBgEIgGgFIgdgQQgEgCgEgFQgEgDgCgFQgCgEAAgHQAAgIAEgGQADgFAGgEQAGgEAHgCQAIgCAIAAQARAAAIAEIAAASQgKgGgOgBIgJACQgEAAgDACQgEABgBADQgDAEAAADQAAAEACADIAFAFIAHAFIAVAKQAFAEAEAEQAFAEACAFQACAFAAAGQAAAIgDAHQgEAFgGAEQgGAEgHABQgIACgIAAgAsehMQgJgLgBgTQAAgTAMgMQALgMAQAAQARAAAIAKQAJALAAATIAAAHIg2AAQAAALAHAGQAGAGAMAAQANAAALgIIAAAPQgMAHgRAAQgTAAgKgLgArwhzQAAgKgFgFQgEgGgIABQgIgBgGAGQgEAGgCAJIAlAAIAAAAgAvxhRQgPgQAAgZQAAgbAPgQQAPgQAZAAQAYAAAPAPQAOARgBAYQAAAcgOAQQgPAQgZAAQgXAAgPgQgAviiZQgLALAAATQAAATAKALQAKAMAOAAQAQAAAKgLQAJgLAAgUQABgTgKgLQgJgLgQAAQgPgBgJAMgAOuhDIAAhQIASAAIAABQgAOFhDIAAgrQABgNgEgGQgEgFgIAAQgHgBgGAIQgEAHAAAKIAAArIgSAAIAAgtQAAgXgQABQgIgBgEAIQgFAGAAALIAAArIgSAAIAAhQIASAAIAAANQAJgPARAAQAIAAAGAFQAGAFACAGQAKgQARAAQAaAAAAAhIAAAxgAL4hDIAAgrQAAgNgEgGQgDgFgJAAQgHgBgFAIQgFAHAAAKIAAArIgSAAIAAgtQAAgXgQABQgHgBgFAIQgFAGAAALIAAArIgSAAIAAhQIASAAIAAANQAJgPARAAQAIAAAHAFQAFAFADAGQAJgQASAAQAaAAAAAhIAAAxgAGKhDIAAh3IASAAIAAB3gABkhDIAAhQIASAAIAAAQQAEgIAFgEQAGgFAGgBQAFAAACACIAAARQgCgDgHAAQgIABgFAHQgGAHAAAMIAAAngAA7hDIAAhQIASAAIAABQgAgOhDIgohwIAVAAIAbBVIADAJIAAAAIACgJIAbhVIAUAAIgoBwgAkxhDIAAhQIASAAIAAAQQADgIAFgEQAGgFAGgBQAGAAACACIAAARQgDgDgGAAQgJABgEAHQgGAHAAAMIAAAngAqYhDIAAgtQAAgXgQABQgIAAgFAGQgGAGAAAJIAAAuIgSAAIAAhQIASAAIAAANIAAAAQAKgPAQAAQAOAAAGAIQAHAJAAAQIAAAxgAOvinQgDgDAAgEQAAgEADgDQADgEAFAAQAEAAAEAEQADADAAAEQAAAEgDADQgEADgEAAQgFAAgDgDgAA9inQgEgDAAgEQAAgEAEgDQADgEAEAAQAFAAADAEQADADAAAEQAAAEgDADQgDADgFAAQgEAAgDgDg");
	this.shape.setTransform(119.4,26.05);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_text2c, new cjs.Rectangle(14.3,0,238.2,50.5), null);


(lib.mc_text2b = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1_copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3C3C41").s().p("ADnBOIAAh0IASAAIAAAPQAKgRASABQAPgBAIALQAJALAAASQAAATgKAMQgJAMgRAAQgPAAgJgNIAAAwgAD/gSQgGAHAAAKIAAAJQAAAJAGAGQAFAGAJAAQAKAAAGgIQAFgHAAgOQAAgMgFgGQgFgHgJAAQgKAAgGAHgAJMA+IAJgnIARAAIgMAngAIMAnIAAgRQAKAIAMAAQAQAAAAgJQAAgEgBgCIgEgDIgVgJIgHgEIgEgHIgBgIQAAgGACgEQADgFAFgDQAEgCAGgCIAMgBQALgBAJAEIAAAQQgIgGgLAAIgGABIgFACIgDADIgBADIABAFQAAAAAAABQABAAAAABQABAAAAAAQABABAAAAIAFACIAHADIAJAEIAHAFQADACACAEQABADAAAFQAAAHgCAEQgDAEgFADQgFAEgGABQgGACgHgBQgNAAgJgEgAHcAVIAAgsIgNAAIAAgPIANAAIAAgSIASgFIAAAXIATAAIAAAPIgTAAIAAAmQAAAIADADQACADAGAAQAFAAADgDIAAAPQgFACgJAAQgXABAAgXgAFMAhQgKgMAAgTQAAgSALgMQALgMAQABQARAAAJAKQAJALAAASIAAAHIg3AAQABAKAGAHQAHAFALABQANAAALgIIAAAOQgLAIgSgBQgSABgKgLgAF5gFQAAgKgEgFQgFgGgIAAQgIAAgFAGQgFAFgCAKIAlAAIAAAAgABHAhQgKgMAAgTQAAgSALgMQALgMAQABQARAAAJAKQAJALAAASIAAAHIg3AAQABAKAGAHQAHAFALABQANAAALgIIAAAOQgLAIgSgBQgSABgKgLgAB0gFQAAgKgEgFQgFgGgIAAQgIAAgFAGQgFAFgCAKIAlAAIAAAAgAg5AhQgKgMAAgTQAAgSALgMQAMgMAQABQAQAAAJAKQAIALAAASIAAAHIg1AAQAAAKAHAHQAGAFAMABQAMAAALgIIAAAOQgLAIgSgBQgSABgKgLgAgLgFQAAgKgFgFQgEgGgIAAQgIAAgGAGQgFAFgBAKIAlAAIAAAAgAjPAVIAAgsIgNAAIAAgPIANAAIAAgSIASgFIAAAXIATAAIAAAPIgTAAIAAAmQAAAIADADQACADAGAAQAFAAADgDIAAAPQgFACgJAAQgXABAAgXgAnnAgQgLgLAAgSQAAgUAMgLQALgLAUAAQATgBAKALQALALAAATQAAATgMAMQgLALgTAAQgSAAgMgLgAnZgSQgGAIAAAMQAAANAGAHQAGAHALAAQALAAAFgHQAGgHAAgOQAAgLgGgIQgFgHgLAAQgLAAgGAHgAGcAqIAAhQIASAAIAAARQADgIAGgFQAFgFAHAAQAFAAACABIAAASQgDgDgGAAQgIAAgFAHQgGAIAAALIAAAngADFAqIgSgfIgRAfIgVAAIAbgnIgagpIAVAAIARAhIAAAAIASghIAUAAIgbAoIAbAogAhlAqIAAgrQAAgYgQAAQgIAAgGAHQgFAHAAAKIAAArIgSAAIAAh2IASAAIAAA0IAAAAQAJgPARAAQAbgBAAAhIAAAxgAknAqIAAgrQAAgNgEgFQgEgGgIAAQgHAAgFAHQgFAHAAAKIAAArIgSAAIAAgsQAAgXgQAAQgHAAgFAHQgFAGAAALIAAArIgSAAIAAhQIASAAIAAANQAJgOARAAQAIgBAGAFQAGAFADAHQAJgQARAAQAbgBAAAhIAAAxgAonAqIAAhQIASAAIAAARQADgIAFgFQAGgFAGAAQAFAAADABIAAASQgDgDgGAAQgJAAgFAHQgFAIAAALIAAAngApZAqIAAhBIgNAAIAAgPIANAAIAAgMQAAgNAIgIQAJgGAMAAQAHAAAEABIAAAPQgEgCgFgBQgNABAAAPIAAAKIATAAIAAAPIgTAAIAABBgAJVgVQgDgDAAgFQAAgEADgDQADgDAFAAQAEAAADADQADADAAAEQAAAFgDADQgDAEgEgBQgFABgDgEg");
	this.shape.setTransform(78.175,15.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_text2b, new cjs.Rectangle(14.3,0,238.2,25.3), null);


(lib.mc_text2a = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1_copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3C3C41").s().p("AnSD1IAAgQQANAIAMgBQAdAAgBgcIAAgJIAAAAQgJAQgSAAQgPAAgJgKQgIgMgBgRQAAgVALgMQAJgMAQAAQARAAAHANIAAAAIAAgLIASAAIAABJQAAAsgsABQgPAAgMgGgAnACZQgGAIAAANQAAAMAGAIQAFAGAKAAQAJAAAGgGQAFgHAAgKIAAgLQAAgJgFgFQgFgHgJAAQgKAAgGAIgAi5DpIAIgmIASAAIgMAmgAj6DSIAAgQQALAHAMAAQAQABAAgKQAAgDgCgCIgDgEIgVgJIgHgEIgFgHIgBgIQABgGACgFQADgEAEgDQAFgDAGgBIAMgCQALAAAJADIAAARQgIgHgLAAIgHABIgEACIgEAEIgBADIABAFQABAAAAAAQAAABABAAQAAABABAAQAAAAABAAIAFADIAHADIAJAEIAHAFQADACABAEQACAEAAAFQAAAGgDAEQgDAFgEADQgFADgGACQgGABgHAAQgNAAgKgFgAlFDMQgKgLAAgUQAAgSALgMQAMgMAPAAQARAAAJALQAJAKAAATIAAAHIg2AAQAAALAHAGQAGAGAMAAQAMAAALgHIAAAOQgLAHgSAAQgSAAgKgLgAkXClQgBgJgEgGQgEgFgJgBQgIABgFAFQgFAGgBAJIAlAAIAAAAgAotDMQgLgMAAgSQAAgUALgLQAMgMAUAAQATAAAKALQAKALAAATQAAAUgLAMQgLALgTAAQgTAAgLgLgAofCZQgGAHAAANQAAANAGAIQAGAGAKAAQALAAAGgGQAGgIAAgNQAAgNgGgHQgGgIgLAAQgKAAgGAIgAq2DMQgLgMAAgSQAAgUAMgLQALgMATAAQAUAAAKALQALALAAATQAAAUgMAMQgLALgTAAQgTAAgLgLgAqoCZQgHAHABANQgBANAHAIQAGAGAKAAQALAAAGgGQAGgIAAgNQAAgNgGgHQgGgIgLAAQgKAAgGAIgAu7DMQgLgMAAgRQAAgUAMgMQAMgMATAAQALAAAJAEIAAARQgIgGgKgBQgLABgIAHQgIAIABAMQAAANAGAIQAIAGALAAQAKAAAJgGIAAAPQgKAGgNAAQgSAAgLgLgAwRDMQgKgLAAgUQAAgSALgMQAMgMAPAAQARAAAJALQAJAKAAATIAAAHIg3AAQABALAGAGQAHAGALAAQANAAALgHIAAAOQgLAHgSAAQgSAAgKgLgAvkClQABgJgFgGQgEgFgJgBQgHABgGAFQgFAGgCAJIAlAAIAAAAgAxKDAIAAgtIgOAAIAAgOIAOAAIAAgSIASgGIAAAYIATAAIAAAOIgTAAIAAAoQAAAIACADQADACAGAAQAEAAAEgCIAAAOQgFADgJAAQgYAAABgXgAlzDVIAAhQIASAAIAABQgApcDVIAAh2IASAAIAAB2gArjDVIAAgtQgBgWgPgBQgJABgFAGQgFAGAAAKIAAAtIgSAAIAAhQIASAAIAAANIAAAAQAJgPARAAQANAAAGAJQAIAIAAAQIAAAxgAtBDVIAAgrQAAgZgPAAQgJAAgFAIQgGAHABAKIAAArIgSAAIAAh2IASAAIAAAzIAAAAQAJgPARAAQAaAAAAAgIAAAygAixCWQgDgEAAgEQAAgFADgDQAEgCAEAAQAFAAADACQADADAAAFQAAAEgDAEQgDADgFAAQgEAAgEgDgAlxByQgEgEAAgEQAAgFAEgDQADgCAEAAQAFAAADACQADADAAAFQAAAEgDADQgDADgFAAQgEAAgDgCgAsmBJIAAgRQANAIAMAAQAcAAAAgcIAAgJIAAAAQgJAQgSAAQgPAAgIgLQgJgLAAgSQAAgUAKgLQAJgNARAAQAPAAAIAOIAAAAIAAgLIASAAIAABIQABAsgtAAQgPAAgMgFgAsUgSQgGAHAAANQAAAMAGAHQAFAHAJAAQAKAAAGgHQAGgHgBgKIAAgKQABgIgGgGQgGgGgIAAQgKAAgGAIgAg7BOIAAh0IASAAIAAANQAKgQARAAQAPAAAIAMQAIAKAAASQAAATgJAMQgIAMgRAAQgQAAgIgOIAAAygAgkgTQgFAHAAAKIAAAJQAAAJAFAGQAGAGAJAAQAJAAAGgIQAGgIAAgNQAAgMgFgGQgGgHgIAAQgLAAgGAHgAKNAgQgKgMAAgTQAAgSALgLQAMgNAQAAQAQAAAJALQAJAKAAAUIAAAGIg2AAQAAAKAGAHQAHAFALAAQANAAALgHIAAAOQgLAIgSAAQgSgBgKgKgAK7gHQAAgJgFgFQgFgGgHAAQgJAAgFAGQgFAGgBAIIAlAAIAAAAgAJDAgQgLgMAAgSQAAgSAMgMQAMgNAUAAQALABAHAEIAAARQgHgHgKAAQgMAAgHAIQgIAIAAALQAAAMAHAIQAIAHALAAQAKAAAIgHIAAAQQgJAFgNABQgSgBgLgKgAGkAIIAAguIASAAIAAAtQAAAVARAAQAHAAAGgGQAFgGAAgJIAAgtIASAAIAABPIgSAAIAAgNIAAAAQgIAPgRAAQgcAAAAgjgAFMAfQgLgLAAgTQAAgSALgMQALgMAUAAQATAAALAMQAKAKAAATQAAATgLAMQgLAMgUAAQgSAAgLgMgAFZgSQgGAHAAAMQAAAMAGAIQAHAHAKAAQALAAAFgHQAHgHAAgOQAAgMgHgGQgFgIgLAAQgKAAgHAIgAD8AmIAAgRQALAIAMAAQAQAAAAgKQAAgCgCgCIgDgEIgWgJIgGgEIgFgHIgBgIQABgFACgFQADgFAEgDQAFgDAGgBIAMgCQALAAAJAEIAAAQQgIgGgLAAIgHABIgEABIgEAEIgBAEIABAEQABAAAAABQAAAAABABQAAAAABAAQAAABABAAIAFACIAHADIAJAFIAHADQADADABAEQACAEAAAEQAAAGgDAFQgDAEgEADQgFADgGACQgGABgHABQgNgBgKgEgAApAgQgLgMAAgTQAAgSAMgLQALgNAQAAQAQAAAKALQAIAKABAUIAAAGIg3AAQAAAKAHAHQAGAFAMAAQANAAALgHIAAAOQgMAIgRAAQgTgBgJgKgABWgHQAAgJgFgFQgEgGgIAAQgIAAgGAGQgEAGgCAIIAlAAIAAAAgAiVAfQgLgLAAgTQAAgSALgMQAMgMAUAAQASAAALAMQAKAKAAATQAAATgLAMQgLAMgTAAQgSAAgMgMgAiHgSQgGAHgBAMQABAMAGAIQAGAHALAAQALAAAFgHQAGgHAAgOQAAgMgGgGQgFgIgLAAQgLAAgGAIgAkiAgQgJgLAAgTQAAgSAKgMQAJgNARAAQAQAAAHAOIAAAAIAAgyIASAAIAAB2IgSAAIAAgOIAAAAQgJAQgSAAQgPgBgIgKgAkTgSQgGAHAAAMQAAANAGAHQAFAHAKAAQAJAAAGgHQAGgHgBgKIAAgKQABgIgGgGQgGgGgIAAQgKAAgGAIgAnWAkQgGgHgBgKQAAgVAbgFIAXgCQAAgSgQAAQgPAAgLAKIAAgQQANgIAQAAQAeABAAAeIAAAzIgRAAIAAgNQgJAPgPAAQgMgBgHgGgAm7ADQgIACgFADQgDACAAAHQAAAFADAEQAEACAGAAQAJABAFgGQAFgGAAgJIAAgHgAv3AmIAAgRQAKAIAMAAQAQAAAAgKQAAgCgBgCIgDgEIgWgJIgHgEIgEgHIgBgIQAAgFACgFQADgFAFgDQAEgDAGgBIANgCQAKAAAJAEIAAAQQgIgGgLAAIgGABIgFABIgDAEIgBAEIABAEQAAAAABABQAAAAAAABQABAAAAAAQABABABAAIAEACIAHADIAKAFIAHADQADADABAEQABAEAAAEQAAAGgCAFQgDAEgFADQgEADgHACQgFABgHABQgOgBgJgEgAxRAIIAAguIASAAIAAAtQAAAVARAAQAIAAAGgGQAEgGAAgJIAAgtIASAAIAABPIgSAAIAAgNIAAAAQgIAPgRAAQgcAAAAgjgAICApIAAhPIASAAIAAAQQADgJAGgEQAGgFAGAAQAFAAACACIAAARQgCgDgHAAQgIAAgFAHQgFAIgBALIAAAngACuApIAAgsQAAgXgQAAQgIAAgGAHQgFAFAAAKIAAAtIgSAAIAAhPIASAAIAAANIABAAQAIgPARgBQAOAAAGAJQAHAJAAAPIAAAxgAlOApIAAgsQAAgXgQAAQgIAAgFAHQgGAFAAAKIAAAtIgSAAIAAhPIASAAIAAANIABAAQAJgPARgBQAMAAAHAJQAHAJAAAPIAAAxgAouApIAAhwIASAAIAABwgApSApIgKgdIgsAAIgKAdIgUAAIAqhwIAVAAIApBwgAphgCIgPgtIgCgHIgBAAIgBAHIgQAtIAjAAgAtPApIAAgsQAAgXgQAAQgIAAgFAHQgGAFAAAKIAAAtIgSAAIAAhPIASAAIAAANIAAAAQAKgPARgBQAMAAAHAJQAHAJAAAPIAAAxgAuuApIAAhPIASAAIAABPgAusg6QgDgDgBgEQABgFADgDQADgDAEAAQAFAAADADQADADABAFQgBADgDADQgDAEgFAAQgEgBgDgCgANehfIAAgOIAIABQAKAAAFgKIAFgNIgghQIAVAAIATA6IABAGIABAAIAVhAIASAAIgkBdQgLAZgUAAIgKgCgAiuhfIAAgOIAHABQALAAAEgKIAGgNIgghQIAUAAIATA6IACAGIAAAAIAVhAIASAAIgkBdQgKAZgVAAIgJgCgAmGhjIAAgQQANAHAMABQAdAAAAgcIAAgJIgBAAQgJAPgSAAQgOAAgJgLQgKgKABgTQgBgUAKgMQAKgMARAAQAPAAAIANIABAAIAAgLIASAAIAABKQAAAsgsAAQgRgBgLgFgAl0i/QgGAIAAANQAAANAGAGQAGAIAIgBQAKABAGgIQAGgGAAgLIAAgKQAAgJgGgFQgFgHgJABQgKAAgGAHgAuuheIAAh1IASAAIAAAOQAKgQASAAQAPAAAIALQAJAKAAATQAAATgJAMQgKANgRAAQgPAAgJgOIAAAxgAuWi/QgGAGAAALIAAAKQAAAIAGAGQAFAHAJgBQAKABAGgJQAFgHABgOQAAgMgGgGQgFgIgJABQgKgBgGAIgAQgiGIAAgRQAKAJAMgBQARAAAAgJQAAgDgCgCIgEgEIgVgJIgHgEIgEgHIgBgIQAAgGADgEQADgFAEgDQAEgDAHgCIALgBQAMAAAIAEIAAAPQgIgFgLAAIgGABIgFABIgDADIgBAEIABAEQAAABABAAQAAABAAAAQABABAAAAQABAAABABIAEACIAHACIAJAFIAIAFQACADACADQACAEAAAFQAAAGgDAEQgDAFgEADQgGADgGABQgGACgGAAQgNAAgKgFgAOyiGIAAgRQAKAJAMgBQAQAAAAgJQAAgDgBgCIgDgEIgWgJIgHgEIgEgHIgBgIQAAgGACgEQADgFAFgDQAEgDAGgCIANgBQALAAAIAEIAAAPQgIgFgLAAIgGABIgFABIgDADIgBAEIABAEQAAABABAAQAAABAAAAQABABAAAAQABAAABABIAEACIAHACIAKAFIAHAFQADADABADQABAEAAAFQAAAGgCAEQgDAFgFADQgEADgHABQgFACgHAAQgOAAgJgFgALqiHQgHgHAAgKQAAgXAagEIAYgDQAAgRgQAAQgPgBgLALIAAgRQANgHAQAAQAeAAAAAeIAAA0IgRAAIAAgNQgJAPgQAAQgMAAgGgGgAMEioQgIABgEADQgEACAAAIQAAAEAEAEQADADAHAAQAIAAAFgGQAFgGABgIIAAgHgAI5iHQgHgHABgKQAAgXAZgEIAYgDQAAgRgQAAQgOgBgMALIAAgRQANgHARAAQAdAAABAeIAAA0IgSAAIAAgNQgIAPgRAAQgMAAgGgGgAJTioQgHABgEADQgEACgBAIQABAEAEAEQADADAGAAQAJAAAFgGQAFgGAAgIIAAgHgAG6iHQgHgHAAgKQAAgXAagEIAYgDQAAgRgQAAQgOgBgMALIAAgRQANgHARAAQAeAAAAAeIAAA0IgSAAIAAgNQgJAPgQAAQgMAAgGgGgAHUioQgHABgEADQgFACAAAIQAAAEAFAEQADADAGAAQAIAAAGgGQAFgGAAgIIAAgHgAGEiYIAAgtIgMAAIAAgOIAMAAIAAgTIATgEIAAAXIATAAIAAAOIgTAAIAAAoQAAAHADAEQACACAGAAQAEAAAEgCIAAAOQgGADgIAAQgXAAgBgXgAEtiHQgGgHAAgKQAAgXAagEIAXgDQAAgRgQAAQgOgBgMALIAAgRQANgHARAAQAdAAAAAeIAAA0IgRAAIAAgNQgJAPgPAAQgNAAgGgGgAFHioQgIABgEADQgDACAAAIQAAAEADAEQAEADAGAAQAIAAAGgGQAFgGAAgIIAAgHgADQiMQgJgLAAgSQAAgUAKgMQAKgMAQAAQAQAAAIANIAAAAIAAgyIASAAIAAB3IgSAAIAAgNIAAAAQgJAPgSAAQgPAAgJgLgADgi/QgHAIAAANQAAAMAHAHQAFAIAKgBQAIABAGgIQAGgGAAgLIAAgKQAAgJgGgFQgFgHgIABQgLAAgFAHgAAHijIAAgwIATAAIAAAuQAAAWAQgBQAIABAFgHQAGgFAAgKIAAguIASAAIAABQIgSAAIAAgNIgBAAQgIAPgRAAQgcAAAAgigAhQiNQgLgKAAgTQAAgUALgLQAMgMAUAAQATAAAKALQAKALABAUQAAATgMALQgLAMgTAAQgTAAgLgMgAhCi/QgGAIAAANQAAAMAGAHQAGAIAKgBQALABAGgIQAGgGAAgOQAAgNgGgHQgGgHgLAAQgKAAgGAHgAkiiMQgKgLAAgTQAAgTALgMQALgMAQAAQARAAAJAKQAIALABATIAAAHIg3AAQAAALAHAGQAGAGAMAAQAMAAAMgIIAAAPQgMAHgRAAQgTAAgJgLgAj1izQAAgKgFgFQgEgGgIABQgIgBgGAGQgFAGgBAJIAlAAIAAAAgAoViHQgGgHgBgKQAAgXAbgEIAXgDQAAgRgQAAQgPgBgLALIAAgRQANgHAQAAQAeAAAAAeIAAA0IgRAAIAAgNQgJAPgPAAQgMAAgHgGgAn6ioQgIABgFADQgDACAAAIQAAAEADAEQAEADAGAAQAJAAAFgGQAFgGAAgIIAAgHgAq4iMQgLgMAAgRQAAgUAMgMQAMgMATAAQAMAAAHAEIAAARQgHgGgKAAQgMgBgHAJQgIAHAAANQABAMAGAHQAIAIALgBQAKABAIgIIAAAQQgJAGgNAAQgSAAgLgLgAtJiMQgKgLAAgTQAAgTALgMQALgMARAAQAQAAAJAKQAJALAAATIAAAHIg3AAQABALAGAGQAHAGALAAQANAAALgIIAAAPQgLAHgSAAQgSAAgKgLgAsbizQAAgKgFgFQgFgGgHABQgJgBgFAGQgFAGgCAJIAmAAIAAAAgAwMijIAAgwIASAAIAAAuQAAAWARgBQAHABAGgHQAFgFAAgKIAAguIASAAIAABQIgSAAIAAgNIAAAAQgIAPgRAAQgdAAABgigAxUiGIAAgRQAKAJAMgBQAQAAAAgJQABgDgCgCIgDgEIgWgJIgHgEIgEgHIgBgIQAAgGACgEQADgFAFgDQAFgDAFgCIAMgBQALAAAKAEIAAAPQgJgFgLAAIgGABIgFABIgDADIgBAEIABAEQAAABABAAQAAABAAAAQABABAAAAQABAAAAABIAGACIAHACIAJAFIAGAFQAEADABADQACAEgBAFQABAGgDAEQgDAFgEADQgFADgGABQgHACgHAAQgNAAgJgFgAP7iDIAAhQIASAAIAABQgAM8iDIAAh3IASAAIAAB3gALBiDIAAgtQAAgXgQABQgIAAgGAGQgFAGAAAJIAAAuIgSAAIAAhQIASAAIAAANIABAAQAIgPARAAQAOAAAGAIQAHAJAAAQIAAAxgABmiDIAAhQIASAAIAAAQQADgIAFgEQAGgFAHgBQAFAAACACIAAARQgDgDgGAAQgJABgFAHQgFAHAAAMIAAAngAnCiDIAAhQIASAAIAAAQQADgIAGgEQAFgFAGgBQAFAAADACIAAARQgDgDgGAAQgJABgEAHQgGAHAAAMIAAAngAo+iDIAAgrQABgYgRAAQgHgBgGAIQgGAGAAALIAAArIgSAAIAAh3IASAAIAAA0IABAAQAJgPARAAQAbAAgBAhIAAAxgAr5iDIAAhQIASAAIAAAQQADgIAGgEQAFgFAHgBQAFAAADACIAAARQgEgDgFAAQgJABgFAHQgGAHAAAMIAAAngAP9jnQgDgDgBgEQABgEADgDQADgEAEAAQAFAAADAEQADADABAEQgBAEgDADQgDADgFAAQgEAAgDgDg");
	this.shape.setTransform(127.85,32.45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_text2a, new cjs.Rectangle(14.3,0,282.8,94.3), null);


(lib.mc_text1c = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1_copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3C3C41").s().p("ABXAtIAAgXQAAgQgNAAIAAgLQANgBAAgPIAAgXQAAgXAcgBIAAAMQgNABAAAOIAAAWQAAAQgPADQAPADAAAQIAAAWQAAAIADAEQACAEAIAAIAAAMQgcgBAAgXgAgbBFQAZgdAAgoQAAgmgZgeIAQAAQAYAdgBAoQABAogYAcgAhZBFQgZgcAAgoQAAgoAZgdIAQAAQgZAeAAAmQAAAoAZAdg");
	this.shape.setTransform(109.4,14.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0078D4").s().p("AkrBJIAAgRQANAHALABQAdAAAAgcIAAgJIAAAAQgKAPgRAAQgPAAgJgLQgJgKAAgTQAAgTAKgMQAJgMARAAQAQAAAIANIAAAAIAAgLIASAAIAABJQAAAsgsAAQgQgBgLgEgAkZgTQgHAIAAAMQAAANAHAGQAFAIAJAAQAJAAAGgIQAGgGAAgLIAAgJQAAgJgGgFQgFgHgJABQgJAAgGAHgAD4AeQgLgKAAgTQAAgTAMgLQALgMATAAQAUAAAKALQALALAAATQAAATgMALQgLAMgTAAQgSAAgMgMgAEGgTQgHAIAAAMQAAAMAHAHQAGAIAKAAQAMAAAFgIQAGgGAAgOQAAgMgGgHQgFgHgMAAQgKAAgGAHgAghAfQgJgLgBgTQABgSAKgMQAMgMAQAAQAQAAAIAKQAJALAAATIAAAGIg1AAQAAALAHAGQAGAGALAAQAMAAAMgIIAAAPQgLAHgSAAQgRAAgLgLgAgSgWQgEAGgCAJIAkAAQAAgKgEgFQgFgGgHABQgIgBgGAGgAhaATIAAgsIgNAAIAAgOIANAAIAAgTIASgEIAAAXIATAAIAAAOIgTAAIAAAnQABAHACAEQADACAFABQAFgBADgCIAAAOQgFADgIAAQgYAAAAgXgAioAlIAAgRQAKAJAMgBQAQAAABgJQAAgDgCgCIgDgEIgNgEIgJgFIgHgDIgEgHIgBgIQAAgGADgEQADgFAEgDQAEgDAHgCIAMgBQAKAAAJAEIAAAPQgIgFgLAAIgGABIgFABIgDADIgBAEIABAEQAAABABAAQAAABAAAAQABABAAAAQABAAABABIAEACIAHACIAJAFIAIAEQADADABADQACAEAAAFQAAAGgDAEQgDAFgFADQgEADgHABQgGACgGAAQgOAAgJgFgAl9AfQgKgLAAgTQAAgSALgMQAMgMAQAAQAQAAAJAKQAJALAAATIAAAGIg2AAQAAALAGAGQAHAGALAAQANAAALgIIAAAPQgLAHgSAAQgSAAgKgLgAlugWQgFAGgBAJIAlAAQAAgKgFgFQgFgGgHABQgJgBgFAGgAGTAoIgQg8IgSA8IgSAAIgYhPIAUAAIAOA5IABAHIAAAAIABgHIARg5IARAAIAOA5IABAHIABAAIAPhAIASAAIgYBPgADLAoIAAgsQAAgXgQABQgJAAgFAGQgGAGABAJIAAAtIgSAAIAAhPIASAAIAAANIAAAAQAJgPARAAQANAAAHAIQAGAJABAQIAAAwgAAvAoIAAhPIASAAIAAAQQADgIAFgEQAGgFAHgBQAFAAACACIAAARQgDgDgGAAQgJABgEAHQgGAHAAALIAAAngAjNAoIAAhPIASAAIAABPgAm8AoIAAhPIASAAIAAAQQADgIAFgEQAFgFAHgBQAFAAADACIAAARQgEgDgFAAQgJABgFAHQgGAHABALIAAAngAjLg7QgDgDgBgEQABgEADgDQADgEAEAAQAFAAADAEQADADAAAEQAAAEgDADQgDADgFAAQgEAAgDgDg");
	this.shape_1.setTransform(47.75,15.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_text1c, new cjs.Rectangle(0,0,123.6,25.3), null);


(lib.mc_text1b = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1_copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3C3C41").s().p("ABXAtIAAgXQgBgQgLAAIAAgLQALgBABgPIAAgXQAAgXAbgBIAAAMQgMABAAAOIAAAWQAAAQgPADQAPADAAAQIAAAWQAAAIADAEQADAEAGAAIAAAMQgbgBAAgXgAgbBFQAYgdABgoQgBgmgYgeIAQAAQAYAdAAAoQAAAogYAcgAhZBFQgZgcABgoQgBgoAZgdIAQAAQgZAeAAAmQAAAoAZAdg");
	this.shape.setTransform(55.15,14.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0078D4").s().p("AgqA2QgHgHAAgKQAAgXAagEIAXgDQAAgQgPAAQgOAAgMAJIAAgPQANgIARAAQAdAAAAAdIAAA0IgSAAIAAgMQgIAOgQAAQgMAAgGgGgAgQAVQgHABgEADQgFADAAAHQAAAFAFADQADADAGAAQAIAAAGgFQAEgGAAgJIAAgHgAh7AxQgKgLAAgTQAAgTALgLQAMgMAPAAQARAAAJALQAJAKAAASIAAAHIg3AAQABALAHAGQAGAGAMAAQAMAAALgHIAAAOQgLAHgSAAQgSAAgKgLgAhsgEQgFAFgCAJIAlAAQABgJgFgFQgEgFgJAAQgHAAgGAFgACYA6IAAgtQAAgVgQAAQgIAAgFAGQgGAFAAAKIAAAtIgSAAIAAhPIASAAIAAAOIABAAQAJgQARAAQAMAAAHAJQAHAIAAAPIAAAxgAAoA6IAAhPIASAAIAAARQADgJAFgEQAGgFAHAAQAFAAACABIAAASQgDgDgGAAQgJAAgFAGQgFAHAAANIAAAmgAipA6IAAh1IASAAIAAB1g");
	this.shape_1.setTransform(20.2,13.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_text1b, new cjs.Rectangle(0,0,69.4,25.3), null);


(lib.mc_text1a = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1_copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3C3C41").s().p("ABXAtIAAgXQgBgQgLAAIAAgLQALgBABgPIAAgXQAAgXAcgBIAAAMQgNABAAAOIAAAWQAAAQgPADQAPADAAAQIAAAWQAAAIADAEQADAEAHAAIAAAMQgcgBAAgXgAgbBFQAYgdABgoQgBgmgYgeIAQAAQAYAdAAAoQAAAogYAcgAhZBFQgZgcABgoQgBgoAZgdIAPAAQgYAeAAAmQAAAoAYAdg");
	this.shape.setTransform(69.55,14.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0078D4").s().p("ACsAxQgLgLAAgTQAAgTAMgLQALgMAUAAQATAAAKALQALALAAATQAAATgMAMQgLALgTAAQgSAAgMgLgAC6gBQgGAHAAANQAAAMAGAIQAGAHALAAQALAAAFgHQAGgHAAgOQAAgNgGgGQgFgHgLAAQgLAAgGAHgAByAmIAAgtIgNAAIAAgOIANAAIAAgSIASgFIAAAXIATAAIAAAOIgTAAIAAAnQAAAIADADQACADAGAAQAFAAADgDIAAAOQgFADgJAAQgXAAAAgWgAiQAxQgLgLAAgTQAAgTALgLQAMgMATAAQATAAALALQAKALAAATQAAATgLAMQgLALgTAAQgTAAgLgLgAiCgBQgHAHAAANQAAAMAHAIQAGAHAKAAQALAAAGgHQAGgHAAgOQAAgNgGgGQgGgHgLAAQgKAAgGAHgAAKA6IgPg8IgSA8IgSAAIgYhPIATAAIAPA5IABAHIAAAAIABgHIARg5IAQAAIAOA5IABAHIAAAAIAQhAIARAAIgXBPgAi+A6IAAgrQAAgXgQAAQgIAAgFAHQgGAGAAAKIAAArIgSAAIAAh1IASAAIAAA0IABAAQAJgQARAAQAaAAAAAgIAAAxg");
	this.shape_1.setTransform(27.575,13.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_text1a, new cjs.Rectangle(0,0,83.8,25.3), null);


(lib.mc_text_signup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1_copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiGBJIAAgRQANAHAMABQAdAAAAgcIAAgJIgBAAQgIAPgTAAQgOAAgJgLQgJgKAAgTQAAgTAKgMQAKgMAQAAQAQAAAHANIABAAIAAgLIASAAIAABJQAAAsgsAAQgQgBgMgEgAh0gTQgFAIAAAMQAAANAFAGQAGAIAJAAQAJAAAHgIQAFgGAAgLIAAgJQAAgJgFgFQgGgHgJABQgKAAgGAHgAC+BNIAAh0IASAAIAAAOQAJgQATAAQAPAAAIALQAIAKAAATQAAASgJAMQgJANgRAAQgPAAgJgOIAAAxgADVgTQgFAGAAALIAAAJQAAAIAFAGQAGAHAJAAQAJAAAGgJQAGgHAAgNQAAgMgFgGQgFgIgJABQgKgBgHAIgABfAIIAAgvIATAAIAAAtQAAAWAQAAQAIAAAFgHQAGgFAAgKIAAgtIASAAIAABPIgSAAIAAgMIgBAAQgIAOgRAAQgcAAAAgigAj0AqIgQgEIgGgCIAAgTIAGADIAHAEIAIACIAIABQAMAAAFgFQAGgDAAgIQAAgDgCgEIgFgEIgdgQQgFgCgDgFQgFgDgBgFQgCgEAAgHQgBgIAEgGQAEgFAFgEQAHgEAHgCQAHgCAIAAQASAAAHAEIAAASQgJgGgPgBIgIACQgEAAgDACQgEABgCADQgCAEAAADQAAAEABADIAGAFIAGAFIAWAKQAFAEAEAEQAEAEACAEQADAFAAAGQAAAIgEAHQgDAFgHAEQgFAEgHABQgIACgJAAgAAOAoIAAgsQgBgXgPABQgHAAgGAGQgFAGgBAJIAAAtIgSAAIAAhPIASAAIAAANIABAAQAJgPAQAAQANAAAGAIQAIAJAAAQIAAAwgAiwAoIAAhPIASAAIAABPgAiug7QgEgDAAgEQAAgEAEgDQADgEAEAAQAFAAADAEQADADAAAEQAAAEgDADQgDADgFAAQgEAAgDgDg");
	this.shape.setTransform(29.6,15.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_text_signup, new cjs.Rectangle(0,0,59.2,25.3), null);


(lib.mc_BG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.App_InfraBG();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_BG, new cjs.Rectangle(0,0,300,250), null);


(lib.ClipGroup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgndAFoIAArPMBO6AAAIAALPg");
	mask.setTransform(252.55,35.975);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FDB82B").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape.setTransform(54.85,54.85);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1BA5EC").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_1.setTransform(17.1,54.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#81B822").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_2.setTransform(54.85,17.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#EF512E").s().p("AiqCrIAAlVIFVAAIAAFVg");
	this.shape_3.setTransform(17.1,17.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#737373").s().p("ARJDTQgYgYAAgyIAAieIhsAAIAAD5IhKAAIAAj5Ig0AAIAAg8IA0AAIAAgrQAAgwAgggQAggfAxAAIAYABIASAEIAAA/IgNgFQgJgDgMAAQgXAAgMAPQgMAPAAAbIAAAlIBsAAIAAhFIBKgXIAABcIBJAAIAAA8IhJAAIAACQQAAAcAKAMQAKAMAXAAQAHAAAIgDQALgEAEgDIAAA8QgHAEgQADQgSAEgNAAQgvAAgWgZgAIsDBQgrgqAAhJQAAhNAsgsQAsgtBMAAQBKAAAoArQApArAABJQAABMgsAsQgrAthLAAQhHAAgrgrgAJkAAQgXAaAAAxQAAAwAWAaQAXAaAoAAQApAAAUgaQAVgZAAgzQAAgygWgYQgWgZgmAAQgpAAgVAagAE7DnQgXgFgRgHIAAhIQATANAYAJQAXAIATAAQAZAAALgHQAMgGAAgRQAAgOgMgLQgMgLgigNQgogQgSgWQgRgWAAggQAAgoAigcQAhgbA1AAQAPAAAWAEQAUAEANAFIAABGQgNgKgUgHQgUgHgTAAQgVAAgLAIQgMAJAAANQAAAPAKAJQAKAJAiAOQAsARASAWQARAXAAAeQAAArghAbQgiAbg5AAQgRAAgagFgAgiDBQgqgpAAhKQAAhNArgsQArgtBNAAQBIAAApArQApAsAABIQAABMgsAsQgqAthMAAQhHAAgqgrgAAVAAQgVAaAAAxQAAAxAVAZQAWAaApAAQAnAAAVgaQAVgZAAgzQAAgygWgYQgVgZgnAAQgoAAgWAagAoDDAQgqgrAAhDQAAhKArgwQAsgxBQAAQAUAAAWAGQAVAFAMAHIAABGQgRgNgSgGQgSgHgSAAQgrAAgaAbQgbAdAAAvQAAAvAaAaQAZAaAsAAQAQAAAUgIQATgHARgMIAABDQgTALgVAEQgXAGgZAAQhFAAgrgsgAkEDkIAAk1IBJAAIAAAxIABAAQAJgZAVgOQATgPAdAAIAQABIAMADIAABKQgGgEgLgEQgMgEgPAAQgaAAgTAWQgSAWAAAwIAACcgAqpDkIAAk1IBJAAIAAE1gAs6DkIAAlSIgCAAIiGFSIgxAAIiKlSIgBAAIAAFSIhFAAIAAmvIBsAAIB8E/IABAAICDk/IBoAAIAAGvgAqkiMQgNgNAAgRQAAgSANgMQAOgNASAAQATAAAMANQANANAAARQAAASgNAMQgMAMgTAAQgTAAgNgMg");
	this.shape_4.setTransform(215.575,34.775);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#737373").s().p("AhlB4QgogqAAhLQAAhGAqgvQAqgvBAAAQA/AAAlAnQAjAoAABFIAAAiIjTAAQAFAwAZARQAZATAnAAQAaAAAYgIQAYgHASgOIAAA8QgSALgdAHQgdAIghAAQhHAAgmgqgAgohWQgVATgGAkICKAAQAAgkgRgTQgRgTgeAAQgZAAgWATg");
	this.shape_5.setTransform(490.9,42.15);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#737373").s().p("AhZCdIAAk0IBJAAIAAAwIABAAQAKgZATgOQAUgPAcABIARAAIALADIAABLQgEgEgNgEQgMgFgPAAQgaAAgTAYQgRAWAAAuIAACcg");
	this.shape_6.setTransform(467.25,41.85);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#737373").s().p("AhtB/QgdgfAAhAIAAi8IBKAAIAACyQAAAoAQAUQAQATAeAAQAfAAASgWQASgVABgkIAAiyIBJAAIAAE1IhJAAIAAgpIgCAAQgOAVgZAMQgYAMgdAAQg2AAgbgeg");
	this.shape_7.setTransform(437.65,42.3);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup, new cjs.Rectangle(0,0,505.1,72), null);


(lib.ClipGroup_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("Ar8L9IAA35IX5AAIAAX5g");
	mask_1.setTransform(76.5,76.5);

	// Layer_3
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AkpLBQiJg6hqhqQhqhqg6iJQg8iOAAicQAAibA8iOQA6iJBqhqQBqhqCJg6QCOg8CbAAQCcAACOA8QCJA6BqBqQBqBqA6CJQA8COAACbQAACcg8COQg6CJhqBqQhqBqiJA6QiOA8icAAQibAAiOg8gAjGk5IE9E7Ik5E5IBCBDIF7l8Il+l+g");
	this.shape_8.setTransform(76.5,76.5);

	var maskedShapeInstanceList = [this.shape_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_1, new cjs.Rectangle(0,0,153,153), null);


(lib.Cursor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#0078D4").ss(0.8,1,1).p("AAAhjIAADH");
	this.shape.setTransform(0,9.975);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},5).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,2,22);


(lib.mc_button = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.ClipGroup_1();
	this.instance.parent = this;
	this.instance.setTransform(9.35,9.35,0.1217,0.1217,0,0,0,76.9,76.9);

	this.instance_1 = new lib.mc_text_signup();
	this.instance_1.parent = this;
	this.instance_1.setTransform(50.15,7.9,1,1,0,0,0,29.6,12.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_button, new cjs.Rectangle(0,0,76.9,18.6), null);


// stage content:
(lib.Data_Ai_300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("A3bzhMAu3AAAMAAAAnDMgu3AAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(338));

	// Logo
	this.instance = new lib.ClipGroup();
	this.instance.parent = this;
	this.instance.setTransform(72.85,31.65,0.2215,0.2215,0,0,0,253.5,37.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#737373").s().p("AiBCbIAAgjICfjYIiUAAIAAg6ID3AAIAAAdIihDeICiAAIAAA6g");
	this.shape_1.setTransform(106.9661,32.7256,0.2215,0.2215);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#737373").s().p("AB6DYIgmhrIipAAIglBrIhSAAICjmvIBTAAICjGvgAhBAuICBAAIhAi1IgCAAg");
	this.shape_2.setTransform(98.9806,31.3744,0.2215,0.2215);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.instance}]}).wait(338));

	// Cursor_1
	this.instance_1 = new lib.Cursor();
	this.instance_1.parent = this;
	this.instance_1.setTransform(18.4,90,1,1,0,0,0,0,10);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:104.25},14).wait(12).to({x:31.95,y:114.95},0).to({x:258.85},20).wait(1).to({x:31.95,y:133.15},0).to({x:218.85},19).wait(1).to({x:31.65,y:149.55},0).to({x:130.85},14).to({_off:true},39).wait(218));

	// Mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AAsIIIAAkIIAwAAIAAEIg");
	var mask_graphics_1 = new cjs.Graphics().p("AANIIIAAkIIBuAAIAAEIg");
	var mask_graphics_2 = new cjs.Graphics().p("AgRIIIAAkIICrAAIAAEIg");
	var mask_graphics_3 = new cjs.Graphics().p("AgvIIIAAkIIDnAAIAAEIg");
	var mask_graphics_4 = new cjs.Graphics().p("AhOIIIAAkIIElAAIAAEIg");
	var mask_graphics_5 = new cjs.Graphics().p("AhtIIIAAkIIFjAAIAAEIg");
	var mask_graphics_6 = new cjs.Graphics().p("AiMIIIAAkIIGhAAIAAEIg");
	var mask_graphics_7 = new cjs.Graphics().p("AirIIIAAkIIHfAAIAAEIg");
	var mask_graphics_8 = new cjs.Graphics().p("AjKIIIAAkIIIdAAIAAEIg");
	var mask_graphics_9 = new cjs.Graphics().p("AjoIIIAAkIIJZAAIAAEIg");
	var mask_graphics_10 = new cjs.Graphics().p("AkHIIIAAkIIKXAAIAAEIg");
	var mask_graphics_11 = new cjs.Graphics().p("AkmIIIAAkIILVAAIAAEIg");
	var mask_graphics_12 = new cjs.Graphics().p("AlFIIIAAkIIMTAAIAAEIg");
	var mask_graphics_13 = new cjs.Graphics().p("AlkIIIAAkIINRAAIAAEIg");
	var mask_graphics_14 = new cjs.Graphics().p("AmDIIIAAkIIOOAAIAAEIg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:9.2,y:52}).wait(1).to({graphics:mask_graphics_1,x:12.2821,y:52}).wait(1).to({graphics:mask_graphics_2,x:15.3641,y:52}).wait(1).to({graphics:mask_graphics_3,x:18.4462,y:52}).wait(1).to({graphics:mask_graphics_4,x:21.5289,y:52}).wait(1).to({graphics:mask_graphics_5,x:24.6109,y:52}).wait(1).to({graphics:mask_graphics_6,x:27.693,y:52}).wait(1).to({graphics:mask_graphics_7,x:30.775,y:52}).wait(1).to({graphics:mask_graphics_8,x:33.8571,y:52}).wait(1).to({graphics:mask_graphics_9,x:36.9391,y:52}).wait(1).to({graphics:mask_graphics_10,x:40.0212,y:52}).wait(1).to({graphics:mask_graphics_11,x:43.1038,y:52}).wait(1).to({graphics:mask_graphics_12,x:46.1859,y:52}).wait(1).to({graphics:mask_graphics_13,x:49.2679,y:52}).wait(1).to({graphics:mask_graphics_14,x:52.35,y:52}).wait(324));

	// Text_1_How_to
	this.instance_2 = new lib.mc_text1a();
	this.instance_2.parent = this;
	this.instance_2.setTransform(58.75,88.85,1,1,0,0,0,41.9,12.6);

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},120).wait(218));

	// Mask_copy (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8xIKIAAjEMA5kAAAIAADEg");
	var mask_1_graphics_26 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_27 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_28 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_29 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_30 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_31 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_32 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_33 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_34 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_35 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_36 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_37 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_38 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_39 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_40 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_41 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_42 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_43 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_44 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_45 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_46 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_47 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_48 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_49 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_50 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_51 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_52 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_53 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_54 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_55 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_56 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_57 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_58 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_59 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_60 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_61 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_62 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_63 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_64 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_65 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_66 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_67 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_68 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_69 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_70 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_71 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_72 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_73 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_74 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_75 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_76 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_77 = new cjs.Graphics().p("EgorAMVIAAilIPtAAIAAClgEgonAJqIAAilMAtXAAAIAAClgEgolAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_78 = new cjs.Graphics().p("EgoIAMVIAAilIPtAAIAAClgEgoEAJqIAAilMAtXAAAIAAClgEgoDAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_79 = new cjs.Graphics().p("EgnkAMVIAAilIPtAAIAAClgEgngAJqIAAilMAtXAAAIAAClgEgnfAHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_80 = new cjs.Graphics().p("EgnAAMVIAAilIPtAAIAAClgEgm8AJqIAAilMAtXAAAIAAClgEgm7AHCIAAi1MBRRAAAIAAC1g");
	var mask_1_graphics_81 = new cjs.Graphics().p("EgmcAMVIAAilIPtAAIAAClgEgmYAJqIAAilMAtXAAAIAAClgEgmXAHCIAAi1MBRRAAAIAAC1g");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:-152.65,y:72.125}).wait(26).to({graphics:mask_1_graphics_26,x:-228.725,y:78.875}).wait(1).to({graphics:mask_1_graphics_27,x:-217.375,y:78.875}).wait(1).to({graphics:mask_1_graphics_28,x:-206.025,y:78.875}).wait(1).to({graphics:mask_1_graphics_29,x:-194.625,y:78.875}).wait(1).to({graphics:mask_1_graphics_30,x:-183.275,y:78.875}).wait(1).to({graphics:mask_1_graphics_31,x:-171.925,y:78.875}).wait(1).to({graphics:mask_1_graphics_32,x:-160.575,y:78.875}).wait(1).to({graphics:mask_1_graphics_33,x:-149.225,y:78.875}).wait(1).to({graphics:mask_1_graphics_34,x:-137.825,y:78.875}).wait(1).to({graphics:mask_1_graphics_35,x:-126.475,y:78.875}).wait(1).to({graphics:mask_1_graphics_36,x:-115.125,y:78.875}).wait(1).to({graphics:mask_1_graphics_37,x:-103.775,y:78.875}).wait(1).to({graphics:mask_1_graphics_38,x:-92.425,y:78.875}).wait(1).to({graphics:mask_1_graphics_39,x:-81.025,y:78.875}).wait(1).to({graphics:mask_1_graphics_40,x:-69.675,y:78.875}).wait(1).to({graphics:mask_1_graphics_41,x:-58.325,y:78.875}).wait(1).to({graphics:mask_1_graphics_42,x:-46.975,y:78.875}).wait(1).to({graphics:mask_1_graphics_43,x:-35.625,y:78.875}).wait(1).to({graphics:mask_1_graphics_44,x:-24.225,y:78.875}).wait(1).to({graphics:mask_1_graphics_45,x:-12.875,y:78.875}).wait(1).to({graphics:mask_1_graphics_46,x:-1.525,y:78.875}).wait(1).to({graphics:mask_1_graphics_47,x:-1.525,y:78.875}).wait(1).to({graphics:mask_1_graphics_48,x:8.475,y:78.875}).wait(1).to({graphics:mask_1_graphics_49,x:18.425,y:78.875}).wait(1).to({graphics:mask_1_graphics_50,x:28.425,y:78.875}).wait(1).to({graphics:mask_1_graphics_51,x:38.375,y:78.875}).wait(1).to({graphics:mask_1_graphics_52,x:48.375,y:78.875}).wait(1).to({graphics:mask_1_graphics_53,x:58.375,y:78.875}).wait(1).to({graphics:mask_1_graphics_54,x:68.325,y:78.875}).wait(1).to({graphics:mask_1_graphics_55,x:78.325,y:78.875}).wait(1).to({graphics:mask_1_graphics_56,x:88.275,y:78.875}).wait(1).to({graphics:mask_1_graphics_57,x:98.275,y:78.875}).wait(1).to({graphics:mask_1_graphics_58,x:108.225,y:78.875}).wait(1).to({graphics:mask_1_graphics_59,x:118.225,y:78.875}).wait(1).to({graphics:mask_1_graphics_60,x:128.225,y:78.875}).wait(1).to({graphics:mask_1_graphics_61,x:138.175,y:78.875}).wait(1).to({graphics:mask_1_graphics_62,x:148.175,y:78.875}).wait(1).to({graphics:mask_1_graphics_63,x:158.125,y:78.875}).wait(1).to({graphics:mask_1_graphics_64,x:168.125,y:78.875}).wait(1).to({graphics:mask_1_graphics_65,x:178.075,y:78.875}).wait(1).to({graphics:mask_1_graphics_66,x:188.075,y:78.875}).wait(1).to({graphics:mask_1_graphics_67,x:188.075,y:78.875}).wait(1).to({graphics:mask_1_graphics_68,x:195.275,y:78.875}).wait(1).to({graphics:mask_1_graphics_69,x:202.475,y:78.875}).wait(1).to({graphics:mask_1_graphics_70,x:209.675,y:78.875}).wait(1).to({graphics:mask_1_graphics_71,x:216.875,y:78.875}).wait(1).to({graphics:mask_1_graphics_72,x:224.075,y:78.875}).wait(1).to({graphics:mask_1_graphics_73,x:231.275,y:78.875}).wait(1).to({graphics:mask_1_graphics_74,x:238.475,y:78.875}).wait(1).to({graphics:mask_1_graphics_75,x:245.675,y:78.875}).wait(1).to({graphics:mask_1_graphics_76,x:252.875,y:78.875}).wait(1).to({graphics:mask_1_graphics_77,x:260.075,y:78.875}).wait(1).to({graphics:mask_1_graphics_78,x:263.825,y:78.875}).wait(1).to({graphics:mask_1_graphics_79,x:267.425,y:78.875}).wait(1).to({graphics:mask_1_graphics_80,x:271.025,y:78.875}).wait(1).to({graphics:mask_1_graphics_81,x:274.625,y:78.875}).wait(257));

	// Text_2_Deploy_copy
	this.instance_3 = new lib.mc_text2a();
	this.instance_3.parent = this;
	this.instance_3.setTransform(143.05,132.65,1,1,0,0,0,126.2,32.6);
	this.instance_3._off = true;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(26).to({_off:false},0).to({_off:true},94).wait(218));

	// Text_3_semicolon
	this.instance_4 = new lib.mc_text3a();
	this.instance_4.parent = this;
	this.instance_4.setTransform(60.65,162.75,1,1,0,0,0,43.8,12.6);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(14).to({_off:false},0).to({_off:true},106).wait(218));

	// Cursor_2
	this.instance_5 = new lib.Cursor();
	this.instance_5.parent = this;
	this.instance_5.setTransform(18.4,90,1,1,0,0,0,0,10);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(120).to({_off:false},0).to({x:88.65},14).wait(12).to({x:31.95,y:114.95},0).to({x:161.2},16).to({_off:true},29).wait(147));

	// Mask_copy (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_120 = new cjs.Graphics().p("AAsIIIAAkIIAwAAIAAEIg");
	var mask_2_graphics_121 = new cjs.Graphics().p("AAHIIIAAkIIBuAAIAAEIg");
	var mask_2_graphics_122 = new cjs.Graphics().p("AgcIIIAAkIICqAAIAAEIg");
	var mask_2_graphics_123 = new cjs.Graphics().p("AhBIIIAAkIIDoAAIAAEIg");
	var mask_2_graphics_124 = new cjs.Graphics().p("AhlIIIAAkIIEmAAIAAEIg");
	var mask_2_graphics_125 = new cjs.Graphics().p("AiKIIIAAkIIFkAAIAAEIg");
	var mask_2_graphics_126 = new cjs.Graphics().p("AiuIIIAAkIIGhAAIAAEIg");
	var mask_2_graphics_127 = new cjs.Graphics().p("AjTIIIAAkIIHfAAIAAEIg");
	var mask_2_graphics_128 = new cjs.Graphics().p("Aj3IIIAAkIIIcAAIAAEIg");
	var mask_2_graphics_129 = new cjs.Graphics().p("AkcIIIAAkIIJaAAIAAEIg");
	var mask_2_graphics_130 = new cjs.Graphics().p("AlAIIIAAkIIKXAAIAAEIg");
	var mask_2_graphics_131 = new cjs.Graphics().p("AllIIIAAkIILVAAIAAEIg");
	var mask_2_graphics_132 = new cjs.Graphics().p("AmJIIIAAkIIMTAAIAAEIg");
	var mask_2_graphics_133 = new cjs.Graphics().p("AmoIIIAAkIINRAAIAAEIg");
	var mask_2_graphics_134 = new cjs.Graphics().p("AnHIIIAAkIIOPAAIAAEIg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(120).to({graphics:mask_2_graphics_120,x:9.2,y:52}).wait(1).to({graphics:mask_2_graphics_121,x:11.7071,y:52}).wait(1).to({graphics:mask_2_graphics_122,x:14.2141,y:52}).wait(1).to({graphics:mask_2_graphics_123,x:16.7212,y:52}).wait(1).to({graphics:mask_2_graphics_124,x:19.2539,y:52}).wait(1).to({graphics:mask_2_graphics_125,x:21.7609,y:52}).wait(1).to({graphics:mask_2_graphics_126,x:24.268,y:52}).wait(1).to({graphics:mask_2_graphics_127,x:26.775,y:52}).wait(1).to({graphics:mask_2_graphics_128,x:29.2821,y:52}).wait(1).to({graphics:mask_2_graphics_129,x:31.7891,y:52}).wait(1).to({graphics:mask_2_graphics_130,x:34.2962,y:52}).wait(1).to({graphics:mask_2_graphics_131,x:36.8288,y:52}).wait(1).to({graphics:mask_2_graphics_132,x:39.3359,y:52}).wait(1).to({graphics:mask_2_graphics_133,x:41.2679,y:52}).wait(1).to({graphics:mask_2_graphics_134,x:43.15,y:52}).wait(204));

	// Text_1_Learn
	this.instance_6 = new lib.mc_text1b();
	this.instance_6.parent = this;
	this.instance_6.setTransform(58.75,88.85,1,1,0,0,0,41.9,12.6);
	this.instance_6._off = true;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(120).to({_off:false},0).to({_off:true},71).wait(147));

	// Mask_copy (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	var mask_3_graphics_120 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8xIKIAAjEMA5kAAAIAADEg");
	var mask_3_graphics_146 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8xIKIAAjEMA5kAAAIAADEg");
	var mask_3_graphics_147 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8xIKIAAjEMA5kAAAIAADEg");
	var mask_3_graphics_148 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8xIKIAAjEMA5kAAAIAADEg");
	var mask_3_graphics_149 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8yIKIAAjEMA5lAAAIAADEg");
	var mask_3_graphics_150 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8yIKIAAjEMA5lAAAIAADEg");
	var mask_3_graphics_151 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8xIKIAAjEMA5kAAAIAADEg");
	var mask_3_graphics_152 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8yIKIAAjEMA5lAAAIAADEg");
	var mask_3_graphics_153 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8xIKIAAjEMA5kAAAIAADEg");
	var mask_3_graphics_154 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8yIKIAAjEMA5lAAAIAADEg");
	var mask_3_graphics_155 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8yIKIAAjEMA5lAAAIAADEg");
	var mask_3_graphics_156 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8yIKIAAjEMA5lAAAIAADEg");
	var mask_3_graphics_157 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8yIKIAAjEMA5lAAAIAADEg");
	var mask_3_graphics_158 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8yIKIAAjEMA5lAAAIAADEg");
	var mask_3_graphics_159 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8yIKIAAjEMA5lAAAIAADEg");
	var mask_3_graphics_160 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8xIKIAAjEMA5kAAAIAADEg");
	var mask_3_graphics_161 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8yIKIAAjEMA5lAAAIAADEg");
	var mask_3_graphics_162 = new cjs.Graphics().p("A8yLRIAAjEIZPAAIAADEgA8xIKIAAjEMA5kAAAIAADEg");

	this.timeline.addTween(cjs.Tween.get(mask_3).to({graphics:null,x:0,y:0}).wait(120).to({graphics:mask_3_graphics_120,x:-152.65,y:72.125}).wait(26).to({graphics:mask_3_graphics_146,x:-152.65,y:72.125}).wait(1).to({graphics:mask_3_graphics_147,x:-144.8,y:72.125}).wait(1).to({graphics:mask_3_graphics_148,x:-137,y:72.125}).wait(1).to({graphics:mask_3_graphics_149,x:-129.2,y:72.125}).wait(1).to({graphics:mask_3_graphics_150,x:-121.35,y:72.125}).wait(1).to({graphics:mask_3_graphics_151,x:-113.5,y:72.125}).wait(1).to({graphics:mask_3_graphics_152,x:-105.7,y:72.125}).wait(1).to({graphics:mask_3_graphics_153,x:-97.85,y:72.125}).wait(1).to({graphics:mask_3_graphics_154,x:-90.05,y:72.125}).wait(1).to({graphics:mask_3_graphics_155,x:-82.2,y:72.125}).wait(1).to({graphics:mask_3_graphics_156,x:-74.4,y:72.125}).wait(1).to({graphics:mask_3_graphics_157,x:-66.55,y:72.125}).wait(1).to({graphics:mask_3_graphics_158,x:-58.75,y:72.125}).wait(1).to({graphics:mask_3_graphics_159,x:-50.9,y:72.125}).wait(1).to({graphics:mask_3_graphics_160,x:-43.1,y:72.125}).wait(1).to({graphics:mask_3_graphics_161,x:-35.25,y:72.125}).wait(1).to({graphics:mask_3_graphics_162,x:-27.45,y:72.125}).wait(176));

	// Text_2_Expert
	this.instance_7 = new lib.mc_text2b();
	this.instance_7.parent = this;
	this.instance_7.setTransform(143.05,132.65,1,1,0,0,0,126.2,32.6);
	this.instance_7._off = true;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(146).to({_off:false},0).to({_off:true},45).wait(147));

	// Text_3_semicolon_copy
	this.instance_8 = new lib.mc_text3a();
	this.instance_8.parent = this;
	this.instance_8.setTransform(60.65,133.95,1,1,0,0,0,43.8,12.6);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(134).to({_off:false},0).to({_off:true},57).wait(147));

	// SignUp_Button_Vector
	this.instance_9 = new lib.mc_button();
	this.instance_9.parent = this;
	this.instance_9.setTransform(58.35,223.15,1,1,0,0,0,38.5,9.3);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(237).to({_off:false},0).to({alpha:1},11).wait(90));

	// Cursor_3
	this.instance_10 = new lib.Cursor();
	this.instance_10.parent = this;
	this.instance_10.setTransform(18.4,90,1,1,0,0,0,0,10);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(192).to({_off:false},0).to({x:142.05},15).to({_off:true},1).wait(130));

	// Mask_copy (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	var mask_4_graphics_192 = new cjs.Graphics().p("AAsIIIAAkIIAwAAIAAEIg");
	var mask_4_graphics_193 = new cjs.Graphics().p("AADIIIAAkIICCAAIAAEIg");
	var mask_4_graphics_194 = new cjs.Graphics().p("AglIIIAAkIIDTAAIAAEIg");
	var mask_4_graphics_195 = new cjs.Graphics().p("AhPIIIAAkIIEnAAIAAEIg");
	var mask_4_graphics_196 = new cjs.Graphics().p("Ah4IIIAAkIIF5AAIAAEIg");
	var mask_4_graphics_197 = new cjs.Graphics().p("AihIIIAAkIIHLAAIAAEIg");
	var mask_4_graphics_198 = new cjs.Graphics().p("AjKIIIAAkIIIdAAIAAEIg");
	var mask_4_graphics_199 = new cjs.Graphics().p("AjzIIIAAkIIJvAAIAAEIg");
	var mask_4_graphics_200 = new cjs.Graphics().p("AkdIIIAAkIILDAAIAAEIg");
	var mask_4_graphics_201 = new cjs.Graphics().p("AlGIIIAAkIIMVAAIAAEIg");
	var mask_4_graphics_202 = new cjs.Graphics().p("AlvIIIAAkIINnAAIAAEIg");
	var mask_4_graphics_203 = new cjs.Graphics().p("AmYIIIAAkIIO5AAIAAEIg");
	var mask_4_graphics_204 = new cjs.Graphics().p("AnBIIIAAkIIQLAAIAAEIg");
	var mask_4_graphics_205 = new cjs.Graphics().p("AnrIIIAAkIIRfAAIAAEIg");
	var mask_4_graphics_206 = new cjs.Graphics().p("AoUIIIAAkIISxAAIAAEIg");
	var mask_4_graphics_207 = new cjs.Graphics().p("Ao9IIIAAkIIUDAAIAAEIg");

	this.timeline.addTween(cjs.Tween.get(mask_4).to({graphics:null,x:0,y:0}).wait(192).to({graphics:mask_4_graphics_192,x:9.2,y:52}).wait(1).to({graphics:mask_4_graphics_193,x:13.3199,y:52}).wait(1).to({graphics:mask_4_graphics_194,x:17.4399,y:52}).wait(1).to({graphics:mask_4_graphics_195,x:21.5598,y:52}).wait(1).to({graphics:mask_4_graphics_196,x:25.6797,y:52}).wait(1).to({graphics:mask_4_graphics_197,x:29.7997,y:52}).wait(1).to({graphics:mask_4_graphics_198,x:33.9196,y:52}).wait(1).to({graphics:mask_4_graphics_199,x:38.0396,y:52}).wait(1).to({graphics:mask_4_graphics_200,x:42.1604,y:52}).wait(1).to({graphics:mask_4_graphics_201,x:46.2804,y:52}).wait(1).to({graphics:mask_4_graphics_202,x:50.4003,y:52}).wait(1).to({graphics:mask_4_graphics_203,x:54.5203,y:52}).wait(1).to({graphics:mask_4_graphics_204,x:58.6402,y:52}).wait(1).to({graphics:mask_4_graphics_205,x:62.7601,y:52}).wait(1).to({graphics:mask_4_graphics_206,x:66.8801,y:52}).wait(1).to({graphics:mask_4_graphics_207,x:71,y:52}).wait(131));

	// Text_1_register
	this.instance_11 = new lib.mc_text1c();
	this.instance_11.parent = this;
	this.instance_11.setTransform(58.75,88.85,1,1,0,0,0,41.9,12.6);
	this.instance_11._off = true;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(192).to({_off:false},0).wait(146));

	// Mask_copy (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	var mask_5_graphics_207 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH+IAAj8MA5lAAAIAAD8g");
	var mask_5_graphics_208 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH9IAAj7MA5kAAAIAAD7g");
	var mask_5_graphics_209 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH9IAAj7MA5kAAAIAAD7g");
	var mask_5_graphics_210 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_211 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_212 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH9IAAj7MA5kAAAIAAD7g");
	var mask_5_graphics_213 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH9IAAj7MA5kAAAIAAD7g");
	var mask_5_graphics_214 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_215 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_216 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH9IAAj7MA5kAAAIAAD7g");
	var mask_5_graphics_217 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH9IAAj7MA5kAAAIAAD7g");
	var mask_5_graphics_218 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH9IAAj7MA5kAAAIAAD7g");
	var mask_5_graphics_219 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_220 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH9IAAj7MA5kAAAIAAD7g");
	var mask_5_graphics_221 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH9IAAj7MA5kAAAIAAD7g");
	var mask_5_graphics_222 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_223 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_224 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_225 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_226 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_227 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH9IAAj7MA5kAAAIAAD7g");
	var mask_5_graphics_228 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_229 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_230 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_231 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH9IAAj7MA5kAAAIAAD7g");
	var mask_5_graphics_232 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_233 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_234 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH9IAAj7MA5kAAAIAAD7g");
	var mask_5_graphics_235 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH9IAAj7MA5kAAAIAAD7g");
	var mask_5_graphics_236 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_237 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8yH9IAAj7MA5lAAAIAAD7g");
	var mask_5_graphics_238 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH9IAAj7MA5kAAAIAAD7g");
	var mask_5_graphics_239 = new cjs.Graphics().p("A8yL9IAAj7IZPAAIAAD7gA8xH+IAAj8MA5kAAAIAAD8g");

	this.timeline.addTween(cjs.Tween.get(mask_5).to({graphics:null,x:0,y:0}).wait(207).to({graphics:mask_5_graphics_207,x:-158.65,y:76.5428}).wait(1).to({graphics:mask_5_graphics_208,x:-148.25,y:76.5172}).wait(1).to({graphics:mask_5_graphics_209,x:-137.9,y:76.5172}).wait(1).to({graphics:mask_5_graphics_210,x:-127.5,y:76.5172}).wait(1).to({graphics:mask_5_graphics_211,x:-117.15,y:76.5172}).wait(1).to({graphics:mask_5_graphics_212,x:-106.75,y:76.5172}).wait(1).to({graphics:mask_5_graphics_213,x:-96.4,y:76.5172}).wait(1).to({graphics:mask_5_graphics_214,x:-86,y:76.5172}).wait(1).to({graphics:mask_5_graphics_215,x:-75.65,y:76.5172}).wait(1).to({graphics:mask_5_graphics_216,x:-65.25,y:76.5172}).wait(1).to({graphics:mask_5_graphics_217,x:-54.9,y:76.5172}).wait(1).to({graphics:mask_5_graphics_218,x:-44.55,y:76.5172}).wait(1).to({graphics:mask_5_graphics_219,x:-34.15,y:76.5172}).wait(1).to({graphics:mask_5_graphics_220,x:-23.75,y:76.5172}).wait(1).to({graphics:mask_5_graphics_221,x:-13.4,y:76.5172}).wait(1).to({graphics:mask_5_graphics_222,x:-3,y:76.5172}).wait(1).to({graphics:mask_5_graphics_223,x:7.35,y:76.5172}).wait(1).to({graphics:mask_5_graphics_224,x:17.75,y:76.5172}).wait(1).to({graphics:mask_5_graphics_225,x:28.1,y:76.5172}).wait(1).to({graphics:mask_5_graphics_226,x:38.45,y:76.5172}).wait(1).to({graphics:mask_5_graphics_227,x:48.85,y:76.5172}).wait(1).to({graphics:mask_5_graphics_228,x:59.25,y:76.5172}).wait(1).to({graphics:mask_5_graphics_229,x:69.6,y:76.5172}).wait(1).to({graphics:mask_5_graphics_230,x:79.95,y:76.5172}).wait(1).to({graphics:mask_5_graphics_231,x:90.35,y:76.5172}).wait(1).to({graphics:mask_5_graphics_232,x:100.75,y:76.5172}).wait(1).to({graphics:mask_5_graphics_233,x:111.1,y:76.5172}).wait(1).to({graphics:mask_5_graphics_234,x:121.5,y:76.5172}).wait(1).to({graphics:mask_5_graphics_235,x:131.85,y:76.5172}).wait(1).to({graphics:mask_5_graphics_236,x:142.25,y:76.5172}).wait(1).to({graphics:mask_5_graphics_237,x:152.6,y:76.5172}).wait(1).to({graphics:mask_5_graphics_238,x:163,y:76.5172}).wait(1).to({graphics:mask_5_graphics_239,x:173.35,y:76.5428}).wait(99));

	// Text_2_OpenSource
	this.instance_12 = new lib.mc_text2c();
	this.instance_12.parent = this;
	this.instance_12.setTransform(145.05,132.65,1,1,0,0,0,126.2,32.6);
	this.instance_12._off = true;

	var maskedShapeInstanceList = [this.instance_12];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(207).to({_off:false},0).wait(131));

	// Blue_box
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0078D4").s().p("AxhDwIAAjkITHAAIAADkgAxhgLIAAjkMAjDAAAIAADkg");
	this.shape_3.setTransform(138.75,127.2);
	this.shape_3._off = true;

	var maskedShapeInstanceList = [this.shape_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(207).to({_off:false},0).wait(131));

	// Text_3_semicolon_copy
	this.instance_13 = new lib.mc_text3a();
	this.instance_13.parent = this;
	this.instance_13.setTransform(60.65,157.55,1,1,0,0,0,43.8,12.6);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(207).to({_off:false},0).wait(131));

	// BG_Image_Frame3
	this.instance_14 = new lib.mc_BG();
	this.instance_14.parent = this;
	this.instance_14.setTransform(150,125,1,1,0,0,0,150,125);
	this.instance_14.alpha = 0;
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(187).to({_off:false},0).to({alpha:1},11).wait(140));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,124,152,127);
// library properties:
lib.properties = {
	id: '45DE8C686E034CA6AB9036DC2ACC0F9E',
	width: 300,
	height: 250,
	fps: 24,
	color: "#EBEBEB",
	opacity: 1.00,
	manifest: [
		{src:"images/App_InfraBG.jpg", id:"App_InfraBG"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['45DE8C686E034CA6AB9036DC2ACC0F9E'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;